# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2026 Hiago De Franco <hfranco@baylibre.com>

obj-y += cv18xx_ddr.o ddr_pkg_info.o ddr_sys.o cvx16_pinmux.o \
	 ddrc_init.o phy_init.o ddr_patch_regs.o
